services:
  etl:
    build:
      context: .
      dockerfile: etl.Dockerfile
    env_file:
      - docker.env
    depends_on:
      - els
      - pg_db
      - redis

  els:
    image: elasticsearch:8.6.2
    env_file:
      - docker.env
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  pg_db:
    image: postgres:16
    env_file:
      - docker.env
    volumes:
      - $HOME/postgresql/data2:/var/lib/postgresql/data

  redis:
    image: redis

volumes:
  elastic_data: